### ISSUE TITLE
Eklerdeki fotoğrafların görünmeme sorunu

### ISSUE THREAD

**Issue by yusufbalyemez** [yunusem/quran-tft#28]
Pdf 
![Screen Shot 2 01 2024 at 22 36](https://github.com/yunusem/quran-tft/assets/124602727/b99ec683-19ad-4e79-9e9c-448c19e684f4)

Uygulama

![Screen Shot 2 01 2024 at 22 37](https://github.com/yunusem/quran-tft/assets/124602727/44146beb-51ce-4f8e-96f4-d99d31e18fbb)

**Comment by yunusem** [comment]
This needs to be fixed right away if we lost rendering pictures after Apps component introduction
