### ISSUE TITLE
Eklerdeki kuran ayeti referanslarına tıklanıldığında sayfanın başına dönme sorunu

### ISSUE THREAD

**Issue by yusufbalyemez** [yunusem/quran-tft#29]
Ekler kısmında referans verilen kuran ayetine tıklanıldığı ayete gidiyor fakat geri düğmesine tıklanıldığı zaman ekler kısmında o ekin başına gidiyor. Olması gereken konuma geri dönmüyor.

**Comment by yunusem** [comment]
This is normal, History only stores page number, we need to add a mechanism to hold previous DOM locations so that we can restore where the reader left, so this is a feature request not an issue, but thanks anyway.
