### ISSUE TITLE
Ek 26 Ayet Referanslarının Linklenmemesi Sorunu

### ISSUE THREAD

**Issue by yusufbalyemez** [yunusem/quran-tft#36]
![Ek 26 Ayet Referanslarının Linklenmemesi Sorunu](https://github.com/yunusem/quran-tft/assets/124602727/0a23213a-00f0-4b54-9254-fed5c672093f)

**Comment by yunusem** [comment]
This specific area creates a corner case , we need more sophisticated reference parsing mechanism
