### ISSUE TITLE
Dil seçiminde ingilizce ve türkçe textinin select boxta beyaz görünmesi sorunu

### ISSUE THREAD

**Issue by yusufbalyemez** [yunusem/quran-tft#48]
İngilizcenin üzerine gelince Türkçe,  Türkçenin üzerine gelince ingilizce görünmüyor.

![Adsız](https://github.com/yunusem/quran-tft/assets/124602727/3008cc53-31bc-46cd-8e07-9b146ee7f670)

**Comment by yunusem** [comment]
It is the browser issue, not ours currently
